/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jk_ndk002_JniTools */

#ifndef _Included_com_jk_ndk002_JniTools
#define _Included_com_jk_ndk002_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jk_ndk002_JniTools
 * Method:    callJavaStaticMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jk_ndk002_JniTools_callJavaStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_jk_ndk002_JniTools
 * Method:    callJavaInstaceMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jk_ndk002_JniTools_callJavaInstaceMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
