/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jk_ndk001_JniTools */

#ifndef _Included_com_jk_ndk001_JniTools
#define _Included_com_jk_ndk001_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jk_ndk001_JniTools
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jk_ndk001_JniTools_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
